[package]
name = "angora_common"
version = "1.2.2"
authors = ["sp1npx <spinpx@gmail.com>"]
edition = "2018"

[dependencies]
serde="1.0"
serde_derive = "1.0"
bincode = "1.0"
libc = "0.2"
nix = "0.14.1"
failure = "0.1.5"
lazy_static = "1.1"
parse_int = "0.5.0"
once_cell = "1.5.2"